export default [
  {
    id: 1,
    city: `Amsterdam`,
    title: `Beautiful & luxurious apartment at great location`,
    photo: `img/apartment-01.jpg`,
    price: 120,
    type: `Apartment`,
    rating: 4,
    isPremium: true,
    isBookmark: false,
  },
  {
    id: 2,
    city: `Amsterdam`,
    title: `Wood and stone place`,
    photo: `img/room.jpg`,
    price: 80,
    type: `Private room`,
    rating: 4,
    isPremium: false,
    isBookmark: true,
  },
  {
    id: 3,
    city: `Amsterdam`,
    title: `Canal View Prinsengracht`,
    photo: `img/apartment-02.jpg`,
    price: 132,
    type: `House`,
    rating: 4,
    isPremium: false,
    isBookmark: false,
  },
  {
    id: 4,
    city: `Amsterdam`,
    title: `Nice, cozy, warm big bed apartment`,
    photo: `img/apartment-03.jpg`,
    price: 180,
    type: `Hotel`,
    rating: 5,
    isPremium: true,
    isBookmark: false,
  },
];
