export default [
  {
    id: 1,
    city: `City-1`,
    title: `Title-1`,
    photo: `img-1`,
    price: 120,
    type: `Type-1`,
    rating: 4,
    isPremium: true,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: true,
    }
  },
  {
    id: 2,
    city: `City-2`,
    title: `Title-2`,
    photo: `img-1`,
    price: 80,
    type: `Type-2`,
    rating: 4,
    isPremium: false,
    isBookmark: true,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: false,
    }
  },
  {
    id: 3,
    city: `City-3`,
    title: `Title-3`,
    photo: `img-1`,
    price: 132,
    type: `Type-3`,
    rating: 4,
    isPremium: false,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: false,
    }
  },
  {
    id: 4,
    city: `City-4`,
    title: `Title-4`,
    photo: `img-1`,
    price: 180,
    type: `Type-4`,
    rating: 5,
    isPremium: true,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: true,
    }
  },
];
