export default [
  {
    id: 1,
    city: `City-1`,
    title: `Title-1`,
    photo: `img-1`,
    price: 120,
    type: `Type-1`,
    rating: 4,
    isPremium: true,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: true,
    },
    coordinates: [52.3909553943508, 4.85309666406198],
    review: {
      description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      rating: 3,
      name: `Max`,
      date: `December 24, 2018`
    },
  },
  {
    id: 2,
    city: `City-2`,
    title: `Title-2`,
    photo: `img-1`,
    price: 80,
    type: `Type-2`,
    rating: 4,
    isPremium: false,
    isBookmark: true,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: false,
    },
    coordinates: [52.369553943508, 4.85309666406198],
    review: {
      description: `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      rating: 4,
      name: `James`,
      date: `October 20, 2018`
    },
  },
  {
    id: 3,
    city: `City-3`,
    title: `Title-3`,
    photo: `img-1`,
    price: 132,
    type: `Type-3`,
    rating: 4,
    isPremium: false,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: false,
    },
    coordinates: [52.3909553943508, 4.929309666406198],
    review: {
      description: `A quiet cozy and picturesque that hides behind a a river by the unique lightness of Amsterdam. The building is green and from 18th century.`,
      rating: 5,
      name: `Ron`,
      date: `July 14, 2018`
    },
  },
  {
    id: 4,
    city: `City-4`,
    title: `Title-4`,
    photo: `img-1`,
    price: 180,
    type: `Type-4`,
    rating: 5,
    isPremium: true,
    isBookmark: false,
    images: [`img-2`, `img-3`],
    description: [`description`],
    feature: `bedrooms`,
    guests: `adults`,
    inside: [`inside-1`, `inside-2`],
    owner: {
      avatar: `img-4`,
      name: `name`,
      isStar: true,
    },
    coordinates: [52.3809553943508, 4.939309666406198],
    review: {
      description: `An independent House, strategically located between Rembrand Square and National Opera, but where the bustle of the city comes to rest in this alley flowery and colorful.`,
      rating: 4,
      name: `Andrew`,
      date: `October 10, 2017`
    },
  },
];
